# This GitHub Actions workflow is designed to copy specified files into a work directory, package them into a ZIP file, and upload this package to a new pre-release.
# Instructions:
# 1. Save this file as .github/workflows/Package.yml in the root directory of your project.
# 2. This workflow will automatically execute when a push to the main branch occurs.

name: 1.Package

on:
  push:
    branches:
      - main  # Adjust this as needed to trigger on different branches

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Create packaging directory
        run: mkdir -p package
        # Creates a directory called 'package' where files will be copied to and zipped

      - name: Copy files to the packaging directory
        run: |
          cp source/Scr_SimpleDemoBox/SimpleDemoBox.sh package/SimpleDemoBox.sh
          cp source/Cfg_Docker/dockerfile package/dockerfile
          cp README.md package/README.md
        # Copies specified files from your repository to the 'package' directory

      - name: Package files
        run: zip -r package.zip package/
        # Packages the contents of the 'package' directory into a ZIP file named 'package.zip'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'Release v${{ github.run_number }}'
          draft: false
          prerelease: true
        # Creates a new release on GitHub, marking it as a pre-release

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.zip
          asset_name: package.zip
          asset_content_type: application/zip
        # Uploads the packaged ZIP file to the newly created pre-release
